### ISSUE TITLE
Compile not working...

### ISSUE THREAD

**Issue by andrew121410** [hypercubemc-github/HyperFall#1]
root@bigassserver:~/stuff/HyperFall-master# ./hyperfall b
fatal: not a git repository (or any of the parent directories): .git
scripts/build.sh: line 5: pushd: HyperFall-Proxy: No such file or directory
scripts/build.sh: line 6: mvn: command not found
root@bigassserver:~/stuff/HyperFall-master#

**Comment by Justsnoopy30** [comment]
You have to clone the repository with `git clone https://github.com/hypercubemc-github/HyperFall.git`
Then you have to install maven and pushd. Search the internet if you don't know how. Also, you can download automatically precompiled builds from the releases section. https://github.com/hypercubemc-github/HyperFall/releases
You can reopen this if you have done all this and it does not work.
